version: 2
jobs:
  build:
    docker:
      - image: docker:17.03-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.03.0-ce
          docker_layer_caching: true
  test:
    docker:
      - image: circleci/python:2.7
        environment:
          DJANGO_SETTINGS_MODULE: cla_frontend.settings.circle
    steps:
      - checkout
      - run:
          name: Setup Python environment
          command: |
            pip install virtualenv
            virtualenv env-ci
      - restore_cache:
          keys:
            - pip-v2-{{ checksum "requirements/testing.txt" }}
      - run:
          name: Install dependencies
          command: |
            source env-ci/bin/activate
            pip install --requirement requirements/testing.txt
      - save_cache:
          key: pip-v2-{{ checksum "requirements/testing.txt" }}
          paths:
            - "~/.cache/pip"

      - run:
          name: Run unit tests
          command: |
            source env-ci/bin/activate
            python manage.py test --verbosity=2

workflows:
  version: 2
  test:
    jobs:
      - test
      - build
